### ISSUE TITLE
docker-redis-cluster fails to start up (partially)

### ISSUE THREAD

**Issue by melinath** [Grokzen/docker-redis-cluster#55]
docker-redis-cluster is failing to boot up consistently on a linux machine (docker 18.06.0-ce); we're also seeing intermittent errors on mac machines (18.06.1-ce-mac73). Specifically, the cluster seems to come up but only cover about a third of the expected slots.

docker-compose.yml
```
redis_sessions:
  dns: 8.8.8.8
  image: grokzen/redis-cluster:4.0.9
  environment:
    CLUSTER_ONLY: 'true'
```

beginning docker-compose logs from failing linux box
```
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
>>> Creating cluster
>>> Performing hash slots allocation on 6 nodes...
Using 3 masters:
:7000
:7001
:7002
Adding replica :7004 to :7000
Adding replica :7005 to :7001
Adding replica :7003 to :7002
>>> Trying to optimize slaves allocation for anti-affinity
[WARNING] Some slaves are in the same host as their master
M: 55ce20d0ae2671c67f0108044e3f89ac72fa2d7a :7000
   slots:0-5460 (5461 slots) master
M: 6c6565c2a52c289e64363f44a28c1e0ff7980ba6 :7001
   slots:5461-10922 (5462 slots) master
M: 0217470798f829dc14bf263132ca0066e94991e5 :7002
   slots:10923-16383 (5461 slots) master
S: 49ed982815367407e0c4320867b8b74d2227a0e2 :7003
   replicates 0217470798f829dc14bf263132ca0066e94991e5
S: c17fa5d257784134f088c2e6eafde59c79e6a49e :7004
   replicates 55ce20d0ae2671c67f0108044e3f89ac72fa2d7a
S: 45e3c71df75b0d9fabbc8d9c15f122df435721b0 :7005
   replicates 6c6565c2a52c289e64363f44a28c1e0ff7980ba6
/var/lib/gems/2.1.0/gems/redis-3.3.3/lib/redis/client.rb:121:in `call': ERR Invalid node address specified: :7000 (Redis::CommandError)
  from /var/lib/gems/2.1.0/gems/redis-3.3.3/lib/redis.rb:2705:in `block in method_missing'
  from /var/lib/gems/2.1.0/gems/redis-3.3.3/lib/redis.rb:58:in `block in synchronize'
  from /usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
  from /var/lib/gems/2.1.0/gems/redis-3.3.3/lib/redis.rb:58:in `synchronize'
  from /var/lib/gems/2.1.0/gems/redis-3.3.3/lib/redis.rb:2704:in `method_missing'
  from /redis/src/redis-trib.rb:941:in `block in join_cluster'
  from /redis/src/redis-trib.rb:939:in `each'
  from /redis/src/redis-trib.rb:939:in `join_cluster'
  from /redis/src/redis-trib.rb:1431:in `create_cluster_cmd'
  from /redis/src/redis-trib.rb:1830:in `<main>'
Can I set the above configuration? (type 'yes' to accept): >>> Nodes configuration updated
>>> Assign a different config epoch to each node
>>> Sending CLUSTER MEET messages to join the cluster
==> /var/log/supervisor/redis-1.log <==
43:C 18 Oct 17:47:45.690 # Redis version=4.0.9, bits=64, commit=00000000, modified=0, pid=43, just started
43:C 18 Oct 17:47:45.690 # Configuration loaded
43:M 18 Oct 17:47:45.691 * No cluster configuration found, I'm 55ce20d0ae2671c67f0108044e3f89ac72fa2d7a
43:M 18 Oct 17:47:45.696 * Running mode=cluster, port=7000.
43:M 18 Oct 17:47:45.696 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
43:M 18 Oct 17:47:45.696 # Server initialized
43:M 18 Oct 17:47:45.696 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
43:M 18 Oct 17:47:45.696 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create laten...
```

I suspect the key is `ERR Invalid node address specified: :7000 (Redis::CommandError)`. On a working mac box, this error doesn't show up, and CLUSTER MEET has additional output after it detailing the different nodes joining the cluster.

This seems likely to be an issue with how we've configured our container. I did try setting REDIS_CLUSTER_IP=0.0.0.0 in docker-compose for the linux user and it did not resolve the issue.

**Comment by Grokzen** [comment]
@melinath I think i might have an idea what the issues could be. Not long ago there was discovered an issue with how IP addresses for the cluster was discovered in the scripts that populate supervisord to run the redis-server services. It was updated in this comimt https://github.com/Grokzen/docker-redis-cluster/commit/423a0e4ff5473ca2f84d0107ba2cbc13491c2e1a to use a better solution. I would suggest you try to update either your fork/clone to use the new solution. I guess that you probably have a much later version of the upstream image `redis:3.2` on your system that uses a later version of the OS it is running on. When we found out about the issue, i did not see the issue on my local machine as i had an very old version of the redis:3.2 tag so the old solution of looking up the IP worked, but when i pulled home the latest version of the upstream image, it broke and i added the above mentioned commit. My theory is that you have the latest version of the redis:3.2 image, but an older version of the code from this repo that fails.

**Comment by Grokzen** [comment]
#52 for reference

**Comment by melinath** [comment]
Thanks, I'll have folks try that as a solution and get back to you about whether it works.

**Comment by Grokzen** [comment]
@melinath Any update on this issue?

**Comment by tandn37** [comment]
I'm not sure it may relate to this issue, but docker-compose down, then up again will work.

**Comment by jindov** [comment]
exactly, docker-compose down and up resolve the issue, but it also flush all data.
If we incidentally restart the docker, it can not work correctly again

**Comment by Grokzen** [comment]
@jindov The data preservation is not part of this container and git-repo. It is intended that it will flush the data and not preserv it between runs.

**Comment by davidfu13** [comment]
The same issue occurred to me, and I have to clean all pre-existing redis data in the container to resolve it.
I can also docker-compose down/up to do the cleaning automatically like @tandn1 suggested. However, to automatically clear the pre-existing redis data in entry point is and alternative solution which might be more error-prone.

**Comment by Grokzen** [comment]
The mentioned PR above is now merged to remove the data from the last run when restarting the container.

**Comment by Grokzen** [comment]
Closing due to inactivity. If issue persist or you find a new issue, please open up a new issue here on Github.
